<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <Compile Remove="gtest\**" />
    <EmbeddedResource Remove="gtest\**" />
    <None Remove="gtest\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="runtimes/linux-x64/native/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.11" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />

    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />

    <PackageReference Include="LibVLCSharp" Version="3.9.7.1" />
    <PackageReference Include="LibVLCSharp.Avalonia" Version="3.9.7.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />

  </ItemGroup>

</Project>